---
title: "test"
author: "Xiaoyu"
date: "2/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(message  = F) 
```

#test
```{r}
library(Seurat)
library(tidyverse)
library(dplyr)
library(stringr)
```
#read
```{r}
aggr.data <- Read10X(data.dir = "aggr")
aggr <- CreateSeuratObject(counts = aggr.data, project = "aggr", min.cells = 3, min.features = 200)
```
#Add meta.data
```{r}
gr=str_split(colnames(aggr),'-',simplify = T)[,2]
table(gr)
timePoints <- sapply(colnames(aggr), function(x) unlist(strsplit(x, "\\-"))[2]) 
timePoints <-ifelse(timePoints == '1', 'Day_2', 
                    ifelse(timePoints == '2', 'Day_4',
                           ifelse(timePoints == '3', 'Day_3', 'Day_0')))
table(timePoints)
aggr <- AddMetaData(object = aggr, metadata = timePoints, col.name = 'TimePoints')
table(aggr@meta.data$TimePoints)
```
#test
```{r}
fivenum(apply(aggr@assays$RNA@counts,1,function(x) sum(x>0) ))
boxplot(apply(aggr@assays$RNA@counts,1,function(x) sum(x>0) ))
fivenum(apply(aggr@assays$RNA@counts,2,function(x) sum(x>0) ))
hist(apply(aggr@assays$RNA@counts,2,function(x) sum(x>0) ))
aggr[["percent.mt"]] <- PercentageFeatureSet(aggr, pattern = "^mt-")
VlnPlot(aggr, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, group.by = 'TimePoints')
head(aggr@meta.data)
```


